version: "2.0"
services:
  elasticsearch:
    image: elasticsearch:5.0
    ports:
      - 9200:9200
  kibana:
    image: kibana:5.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
