#!/bin/sh

#
# Elasticsearch, de l'importance du mapping.
#
# Exercice transposant la présentation éponyne à Devoxx France 2015.
#
# Jérôme Mainaud <jmainaud@ippon.fr>
#
# Licence CC BY-SA 4.0 http://creativecommons.org/licenses/by-sa/4.0/
#

# Données à charger lorsque l'exercice le demande.

# Si nécessaire, adapter le nom du serveur Elasticsearch et son port.
ES=localhost:9200


# DG
#    DSI
#       ARCHI
#       ETUDES
#       SECURITE
#    DRH
#       RECRUTEMENT
#       CARRIERES
#    OPERATIONS
#       VENTES
#       RISQUES

echo -n "load  1 -- "
curl -XPUT $ES/normes/normes/1 -d'
{
  "titre": "Procuration des fournitures",
  "service": "DG"
}'
echo

echo -n "load  2 -- "
curl -XPUT $ES/normes/normes/2 -d'
{
  "titre": "Ouverture des accès réseau",
  "service": "DG/DSI"
}'
echo

echo -n "load  3 -- "
curl -XPUT $ES/normes/normes/3 -d'
{
  "titre": "Couleur des crayons pour schemas",
  "service": "DG/DSI/ARCHITECTURE"
}'
echo

echo -n "load  4 -- "
curl -XPUT $ES/normes/normes/4 -d'
{
  "titre": "Organiser une réunion avec le métier",
  "service": "DG/DSI/ETUDES"
}'
echo

echo -n "load  5 -- "
curl -XPUT $ES/normes/normes/5 -d'
{
  "titre": "Interdire d\u0027abord, autoriser jamais",
  "service": "DG/DSI/SECURITE"
}'
echo

echo -n "load  6 -- "
curl -XPUT $ES/normes/normes/6 -d'
{
  "titre": "Définir les métiers entreprise",
  "service": "DG/DRH"
}'
echo

echo -n "load  7 -- "
curl -XPUT $ES/normes/normes/7 -d'
{
  "titre": "Passe ton bac d\u0027abord",
  "service": "DG/DRH/RECRUTEMENT"
}'
echo

echo -n "load  8 -- "
curl -XPUT $ES/normes/normes/8 -d'
{
  "titre": "Devenir chef de projet",
  "service": "DG/DRH/CARRIERES"
}'
echo

echo -n "load  9 -- "
curl -XPUT $ES/normes/normes/9 -d'
{
  "titre": "Attitude à tenir face au client",
  "service": "DG/OPERATIONS/VENTES"
}'
echo

echo -n "load 10 -- "
curl -XPUT $ES/normes/normes/10 -d'
{
  "titre": "Organiser ses ventes",
  "service": "DG/OPERATIONS/VENTES"
}'
echo
